[workspace]
authors = ["igamenovoer <igamenovoer@xx.com>"]
channels = ["conda-forge"]
name = "genie3-survey"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
capture-html = "python scripts/capture_html.py"
install-browsers = "python -m playwright install chromium"

[dependencies]
python = ">=3.13.5,<3.14"
mypy = ">=1.17.1,<2"
ruff = ">=0.12.7,<0.13"
nodejs = ">=24.4.1,<24.5"

[pypi-dependencies]
playwright = ">=1.54.0,<2"
markitdown = { version = ">=0.1.2, <0.2", extras = ["all"] }
pymupdf = ">=1.26.3, <2"
